export type Product = {
  slug: string;
  group: "seguros" | "planos-de-saude" | "consorcios";
  name: string;
  shortName: string;
  eyebrow: string;
  description: string;
  audience: string;
  benefits: string[];
  steps: string[];
  partners: string[];
  icon: string;
  cities: string[];
};

const coreCities = ["Monsenhor Paulo", "Varginha", "Campanha", "Três Corações", "Três Pontas", "Elói Mendes", "Machado", "Alfenas"];
const extendedCities = ["Pouso Alegre", "Lavras", "Poços de Caldas", "São Lourenço", "Caxambu", "Boa Esperança", "Divinópolis", "Pará de Minas", "Belo Horizonte"];

export const serviceCities = [...coreCities, "Paraguaçu", "Nepomuceno", "Carmo da Cachoeira", "São Gonçalo do Sapucaí", "Lambari", "Cambuquira", "Conceição do Rio Verde", ...extendedCities];

export const products: Product[] = [
  { slug:"seguro-residencial",group:"seguros",name:"Seguro Residencial",shortName:"Casa",eyebrow:"Seu patrimônio protegido",description:"Proteção para a estrutura da residência, bens e imprevistos do dia a dia, com assistências que ajudam quando você mais precisa.",audience:"Proprietários, inquilinos, casas de temporada e imóveis alugados.",benefits:["Incêndio, raio e explosão","Danos elétricos e vendaval","Roubo ou furto qualificado","Responsabilidade civil familiar","Assistências residenciais"],steps:["Entendemos o imóvel e sua utilização","Dimensionamos estrutura e conteúdo","Comparamos coberturas e assistências","Você escolhe e recebe a apólice"],partners:["Allianz","Tokio Marine","Bradesco Seguros"],icon:"⌂",cities:coreCities },
  { slug:"seguro-de-vida",group:"seguros",name:"Seguro de Vida",shortName:"Vida",eyebrow:"Proteção para quem importa",description:"Planejamento financeiro para proteger sua família e oferecer suporte em situações de morte, invalidez, doenças graves e internação, conforme o plano contratado.",audience:"Pessoas, famílias, profissionais autônomos, sócios e empresas.",benefits:["Morte natural ou acidental","Invalidez por acidente ou doença","Diagnóstico de doenças graves","Diárias de internação","Assistência funeral e benefícios em vida"],steps:["Mapeamos renda, dependentes e objetivos","Definimos capitais e coberturas","Comparamos Tokio, Allianz e Bradesco","Acompanhamos proposta e vigência"],partners:["Tokio Marine","Allianz","Bradesco Seguros"],icon:"♥",cities:[...coreCities,...extendedCities] },
  { slug:"seguro-empresarial",group:"seguros",name:"Seguro Empresarial Allianz",shortName:"Empresas",eyebrow:"Proteção para o negócio continuar",description:"Seguro Allianz para proteger patrimônio, operação, equipamentos, mercadorias e responsabilidades da empresa com uma estrutura adequada ao segmento.",audience:"Comércios, escritórios, clínicas, academias, oficinas, indústrias e prestadores de serviço.",benefits:["Incêndio, raio e explosão","Danos elétricos e vendaval","Roubo de bens e mercadorias","Lucros cessantes e despesas fixas","Responsabilidade civil e assistências"],steps:["Levantamos atividade e valores em risco","Identificamos exposições críticas","Estruturamos a proposta Allianz","Revisamos limites, franquias e documentos"],partners:["Allianz"],icon:"▦",cities:[...coreCities,...extendedCities] },
  { slug:"seguro-rural-agricola",group:"seguros",name:"Seguro Rural e Agrícola",shortName:"Agro",eyebrow:"Proteção para produzir",description:"Soluções para propriedades, benfeitorias, máquinas e atividades agrícolas diante de eventos climáticos, incêndio e outros riscos contratados.",audience:"Produtores rurais, fazendas, sítios, cooperativas e empresas do agronegócio.",benefits:["Benfeitorias e instalações rurais","Máquinas e implementos","Incêndio, vendaval e eventos climáticos","Responsabilidade civil rural","Soluções ajustadas à atividade"],steps:["Conhecemos a propriedade e a cultura","Inventariamos bens e equipamentos","Selecionamos riscos e limites","Acompanhamos inspeção e emissão"],partners:["Allianz","Tokio Marine"],icon:"✦",cities:[...coreCities,"Boa Esperança","Lavras","Poços de Caldas"] },
  { slug:"seguro-transporte-logistica",group:"seguros",name:"Seguro Transporte e Logística",shortName:"Transportes",eyebrow:"Carga protegida em movimento",description:"Proteção para mercadorias transportadas e responsabilidades do transportador, considerando rotas, tipos de carga, limites e gerenciamento de risco.",audience:"Transportadoras, embarcadores, operadores logísticos e empresas que movimentam mercadorias.",benefits:["Transporte nacional e internacional","Responsabilidades obrigatórias do transportador","Roubo, colisão e acidentes conforme contratação","Averbação e limites por embarque","Gerenciamento de riscos"],steps:["Mapeamos operação, cargas e rotas","Analisamos embarques e sinistros","Definimos limites e gerenciamento","Acompanhamos implantação e averbações"],partners:["Allianz","Tokio Marine","AKAD"],icon:"▰",cities:[...coreCities,...extendedCities] },
  { slug:"seguro-maquinas-e-equipamentos",group:"seguros",name:"Seguro Máquinas e Equipamentos",shortName:"Equipamentos",eyebrow:"Patrimônio produtivo protegido",description:"Proteção para máquinas móveis, equipamentos industriais, agrícolas, médicos e eletrônicos contra danos de causa externa e riscos contratados.",audience:"Indústrias, clínicas, academias, produtores, construtoras e prestadores de serviço.",benefits:["Danos de causa externa","Roubo ou furto qualificado","Operação e movimentação","Equipamentos móveis ou estacionários","Coberturas dimensionadas por equipamento"],steps:["Relacionamos máquinas e valores","Validamos uso, local e mobilidade","Escolhemos coberturas e franquias","Organizamos documentos para emissão"],partners:["Allianz","Tokio Marine"],icon:"⚙",cities:[...coreCities,...extendedCities] },
  { slug:"responsabilidade-civil-profissional",group:"seguros",name:"Responsabilidade Civil Profissional AKAD",shortName:"RC Profissional",eyebrow:"Proteção para sua atuação",description:"Seguro AKAD para proteger profissionais e empresas diante de reclamações por erros, omissões ou falhas profissionais cobertas.",audience:"Dentistas, médicos, profissionais da saúde, advogados, contadores, engenheiros, arquitetos e consultores.",benefits:["Danos materiais, corporais e morais","Despesas de defesa","Erros e omissões profissionais","Danos estéticos quando contratados","Extensão para pessoa jurídica"],steps:["Entendemos profissão e procedimentos","Analisamos faturamento e histórico","Dimensionamos limite e participação","Emitimos e acompanhamos a apólice AKAD"],partners:["AKAD"],icon:"§",cities:[...coreCities,...extendedCities] },
  { slug:"seguro-oficinas-centros-automotivos",group:"seguros",name:"Seguro para Oficinas e Centros Automotivos",shortName:"Oficinas",eyebrow:"Proteção para o seu pátio",description:"Seguro empresarial estruturado para proteger imóvel, equipamentos, mercadorias, operação e veículos de clientes sob responsabilidade da oficina.",audience:"Oficinas mecânicas, auto centers, borracharias, centros de estética e concessionárias.",benefits:["Incêndio, roubo e danos elétricos","Equipamentos e mercadorias","Guarda de veículos de clientes","Testes e circulação quando contratados","Responsabilidade civil de operações"],steps:["Levantamos estrutura e serviços","Mapeamos veículos sob guarda","Dimensionamos patrimônio e RC","Apresentamos a proposta Allianz"],partners:["Allianz"],icon:"⌁",cities:[...coreCities,...extendedCities] },
  { slug:"seguro-cibernetico",group:"seguros",name:"Seguro Cibernético",shortName:"Cyber",eyebrow:"Resposta para riscos digitais",description:"Proteção financeira e suporte especializado para incidentes cibernéticos, vazamentos, interrupções e responsabilidades relacionadas a dados.",audience:"Empresas que armazenam dados, vendem online ou dependem de sistemas para operar.",benefits:["Resposta a incidentes","Restauração de dados e sistemas","Responsabilidade por privacidade","Interrupção de negócios","Investigação e suporte especializado"],steps:["Avaliamos operação e dados tratados","Identificamos controles existentes","Dimensionamos limites e franquias","Comparamos cobertura e serviços"],partners:["Allianz"],icon:"◈",cities:[...coreCities,...extendedCities] },
  { slug:"acidentes-pessoais",group:"seguros",name:"Seguro Acidentes Pessoais",shortName:"Acidentes",eyebrow:"Proteção simples e acessível",description:"Coberturas para morte ou invalidez causada por acidente, com opções individuais, coletivas e para eventos ou atividades específicas.",audience:"Pessoas, empresas, equipes, prestadores, alunos e participantes de eventos.",benefits:["Morte acidental","Invalidez permanente por acidente","Despesas médicas por acidente","Assistência funeral","Planos individuais ou coletivos"],steps:["Definimos pessoas e atividade","Escolhemos capitais e coberturas","Avaliamos vigência e abrangência","Formalizamos a contratação"],partners:["Tokio Marine","Allianz","Bradesco Seguros"],icon:"✚",cities:[...coreCities,...extendedCities] },
  { slug:"individual-e-familiar",group:"planos-de-saude",name:"Plano de Saúde Individual e Familiar",shortName:"Saúde Familiar",eyebrow:"Cuidado para cada fase da vida",description:"Comparação de planos, redes, acomodações, coparticipação, carências e abrangência para encontrar uma opção adequada à sua família.",audience:"Pessoas, casais, famílias, profissionais liberais e clientes por adesão elegível.",benefits:["Rede médica e hospitalar","Consultas, exames e internações","Opções com ou sem coparticipação","Abrangência regional ou nacional","Orientação sobre carências e reembolso"],steps:["Entendemos idades e cidades de uso","Comparamos rede e acomodação","Explicamos carências e coparticipação","Apoiamos a implantação do plano"],partners:["Unimed","Azul Saúde","Bradesco Saúde","Amil","SulAmérica","Qualicorp"],icon:"✚",cities:[...coreCities,...extendedCities] },
  { slug:"empresarial",group:"planos-de-saude",name:"Plano de Saúde Empresarial",shortName:"Saúde Empresarial",eyebrow:"Benefício que atrai e retém",description:"Planos para empresas e equipes, considerando número de vidas, cidades atendidas, rede, coparticipação e equilíbrio de custo.",audience:"MEIs elegíveis, pequenas e médias empresas e organizações com equipes em Minas Gerais.",benefits:["Condições por número de vidas","Rede regional ou nacional","Coparticipação configurável","Inclusão de dependentes conforme regras","Apoio na escolha e implantação"],steps:["Levantamos CNPJ, vidas e idades","Mapeamos cidades e rede necessária","Comparamos operadoras e custos","Orientamos documentação e implantação"],partners:["Unimed","Azul Saúde","Bradesco Saúde","Amil","SulAmérica","Qualicorp"],icon:"✚",cities:[...coreCities,...extendedCities] },
  { slug:"automoveis",group:"consorcios",name:"Consórcio de Automóveis Rodobens",shortName:"Consórcio Auto",eyebrow:"Planeje seu próximo veículo",description:"Compra programada de carros e motos com cartas de crédito Rodobens, contemplação por sorteio ou lance e parcelas planejadas.",audience:"Pessoas e empresas que podem planejar a aquisição ou renovação de veículos.",benefits:["Cartas para carros e motos","Contemplação por sorteio ou lance","Poder de compra à vista após contemplação","Prazos e créditos variados","Acompanhamento da estratégia de lance"],steps:["Definimos crédito e prazo","Simulamos parcelas e taxa administrativa","Explicamos sorteios e tipos de lance","Acompanhamos adesão e planejamento"],partners:["Rodobens"],icon:"◉",cities:[...coreCities,...extendedCities] },
  { slug:"imoveis",group:"consorcios",name:"Consórcio de Imóveis Rodobens",shortName:"Consórcio Imóvel",eyebrow:"Patrimônio com planejamento",description:"Carta de crédito para aquisição, construção, reforma ou outras utilizações admitidas no grupo, sem juros de financiamento e com taxa administrativa.",audience:"Quem busca comprar, construir, reformar ou ampliar patrimônio com planejamento de longo prazo.",benefits:["Cartas para imóveis","Compra, construção ou reforma conforme regras","Sorteios e ofertas de lance","Possibilidade de uso de FGTS conforme normas","Planejamento sem juros de financiamento"],steps:["Definimos objetivo e crédito","Avaliamos prazo e capacidade mensal","Explicamos contemplação e reajustes","Acompanhamos contratação Rodobens"],partners:["Rodobens"],icon:"⌂",cities:[...coreCities,...extendedCities] },
  { slug:"pesados-maquinas-e-equipamentos",group:"consorcios",name:"Consórcio de Pesados, Máquinas e Equipamentos Rodobens",shortName:"Consórcio Pesados",eyebrow:"Crescimento para sua operação",description:"Planejamento para aquisição ou renovação de caminhões, implementos, máquinas e equipamentos utilizados na empresa ou propriedade rural.",audience:"Transportadoras, produtores rurais, indústrias, construtoras e empresários.",benefits:["Crédito para caminhões e pesados","Máquinas e equipamentos elegíveis","Compra programada para expansão","Sorteio e estratégias de lance","Planejamento de renovação de frota"],steps:["Mapeamos o investimento desejado","Definimos crédito e horizonte","Simulamos parcelas e contemplação","Acompanhamos a contratação Rodobens"],partners:["Rodobens"],icon:"▣",cities:[...coreCities,...extendedCities] },
];

export const autoProduct = { slug:"seguro-automovel",group:"seguros" as const,name:"Seguro Automóvel",shortName:"Auto",description:"Compare seguradoras, coberturas, franquias e assistências com orientação humana.",icon:"◉" };
export function getProduct(group: Product["group"], slug: string){return products.find(p=>p.group===group&&p.slug===slug)}
export function productHref(product: Pick<Product,"group"|"slug">){return `/${product.group}/${product.slug}/`}
