import type { Metadata } from "next";
import LegalPage from "../components/LegalPage";

export const metadata: Metadata = { title: "Política de Privacidade | Vital Corretora de Seguros" };

const sections = [
  { title: "Quem somos", paragraphs: ["A Vital Corretora de Seguros Ltda., inscrita no CNPJ nº 66.767.206/0001-50, atua na intermediação de seguros e na prestação de serviços de assessoria e atendimento.", "Para as finalidades desta Política, atuamos como controladora dos dados pessoais que tratamos e, em determinadas situações, como operadora por conta de seguradoras parceiras."] },
  { title: "A quem esta Política se aplica", paragraphs: ["Esta Política se aplica a todas as pessoas que se relacionam conosco."], bullets: ["Clientes, segurados, beneficiários e representantes legais;", "Interessados que solicitam cotações, simulações ou informações;", "Visitantes do site, landing pages e redes sociais;", "Pessoas que entram em contato por WhatsApp, telefone, e-mail ou formulários;", "Parceiros, prestadores de serviço e candidatos a vagas."] },
  { title: "Quais dados tratamos", paragraphs: ["Tratamos somente os dados necessários para prestar nossos serviços, como dados cadastrais e de contato, informações contratuais e do bem segurado, dados financeiros, registros de comunicação e navegação.", "Dados sensíveis, inclusive informações de saúde, são tratados apenas quando indispensáveis e com a base legal adequada. Não coletamos intencionalmente dados de crianças e adolescentes sem autorização do responsável legal."] },
  { title: "Por que tratamos seus dados", paragraphs: ["Usamos os dados para atender cotações, intermediar contratações, renovações e endossos, acompanhar sinistros, prestar suporte, cumprir obrigações legais e regulatórias, prevenir fraudes e exercer direitos.", "Comunicações de marketing dependem de consentimento ou de outra base legal aplicável e sempre oferecem a possibilidade de descadastro."] },
  { title: "Uso da API oficial do WhatsApp", paragraphs: ["Utilizamos a API oficial do WhatsApp Business para atendimento, avisos e continuidade das negociações. As conversas podem ser armazenadas para histórico, qualidade e comprovação das tratativas.", "Você pode interromper mensagens de marketing a qualquer momento. O tráfego também está sujeito aos termos e à política da Meta Platforms."] },
  { title: "Compartilhamento de dados", paragraphs: ["Podemos compartilhar dados com seguradoras, prestadores de tecnologia e atendimento, instituições financeiras, órgãos públicos e autoridades quando necessário para prestar o serviço ou cumprir obrigação legal.", "Não vendemos dados pessoais. Exigimos dos parceiros medidas compatíveis de segurança e privacidade."] },
  { title: "Transferência internacional de dados", paragraphs: ["Alguns fornecedores de tecnologia podem processar dados fora do Brasil. Nessas situações adotamos mecanismos e salvaguardas previstos na LGPD."] },
  { title: "Por quanto tempo guardamos seus dados", paragraphs: ["Mantemos os dados pelo período necessário às finalidades informadas, ao cumprimento de obrigações legais e regulatórias e ao exercício regular de direitos. Depois disso, os dados são eliminados ou anonimizados quando aplicável."] },
  { title: "Seus direitos como titular", paragraphs: ["Você pode solicitar confirmação e acesso, correção, anonimização, bloqueio ou eliminação, portabilidade, informação sobre compartilhamentos, revisão de decisões automatizadas e revogação de consentimento."], bullets: ["Envie a solicitação para contato@vital.net.br;", "Podemos pedir informações para confirmar sua identidade;", "Responderemos dentro dos prazos previstos na legislação."] },
  { title: "Segurança da informação", paragraphs: ["Adotamos medidas técnicas e administrativas para proteger os dados contra acesso não autorizado, perda, alteração ou divulgação indevida. Nenhum ambiente é totalmente imune, mas revisamos continuamente nossos controles."] },
  { title: "Cookies e tecnologias de rastreamento", paragraphs: ["Podemos usar cookies essenciais, analíticos e de preferência para o funcionamento e aprimoramento do site. Você pode gerenciá-los nas configurações do navegador."] },
  { title: "Alterações desta Política", paragraphs: ["Esta Política pode ser atualizada para refletir mudanças legais, regulatórias ou operacionais. A versão vigente será sempre publicada nesta página com a data de atualização."] },
  { title: "Contato e Encarregado de Dados (DPO)", paragraphs: ["Para dúvidas ou exercício de direitos, entre em contato com Felipe Vital pelo e-mail contato@vital.net.br. Site oficial: www.vital.net.br."] },
];

export default function PrivacyPage() {
  return <LegalPage eyebrow="Privacidade e proteção de dados" title="Política de Privacidade" intro="Este documento explica, de forma clara, como coletamos, usamos, compartilhamos e protegemos seus dados pessoais, em conformidade com a Lei nº 13.709/2018 (LGPD)." counterpartHref="/seguro-automovel/termos-de-uso/" counterpartLabel="Ver Termos de Uso" sections={sections} />;
}
