import WhatsAppLink from "./components/WhatsAppLink";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Vital Corretora | Seguros, Consórcios e Planos de Saúde",
  description: "Proteção para pessoas, famílias e empresas. Conheça o portfólio de seguros e consórcios da Vital Corretora.",
  alternates: { canonical: "/" },
};

const whatsapp = "https://wa.me/553584149766?text=Oi%2C%20quero%20conhecer%20as%20solu%C3%A7%C3%B5es%20da%20Vital%21";
const products = [
  ["Riscos Cibernéticos","/home-products/cibernetico.png","/produtos/riscos-ciberneticos/","Proteção contra ataques digitais, vazamentos e responsabilidades."],
  ["Acidentes de Trabalho","/home-products/acidentes-trabalho.png","/produtos/acidentes-de-trabalho/","Segurança para sua equipe e proteção para a operação."],
  ["Responsabilidade Civil","/home-products/responsabilidade-civil.png","/produtos/responsabilidade-civil/","Cobertura para danos causados durante a atividade profissional."],
  ["Máquinas e Equipamentos","/home-products/maquinas.png","/produtos/maquinas-e-equipamentos/","Proteção para equipamentos industriais, comerciais e móveis."],
  ["Transportes e Logística","/home-products/transportes.png","/produtos/transportes-e-logistica/","Sua carga protegida em cada etapa do transporte."],
  ["Agricultura e Implementos","/home-products/agricultura.png","/produtos/agricultura-e-implementos/","Soluções para a produção, máquinas e patrimônio rural."],
  ["Seguro de Vida","/home-products/vida.png","/produtos/seguro-de-vida/","Cuidado financeiro para você, sua família e sua equipe."],
  ["Seguro Residencial","/home-products/residencial.png","/produtos/seguro-residencial/","Proteção e assistência para cuidar da sua casa."],
  ["Consórcio Rodobens","/home-products/consorcio.png","/produtos/consorcio-rodobens/","Planejamento para conquistar veículos, imóveis e equipamentos."],
];
const insurerLogos = ["mapfre","suhai","yelum","porto","tokio-marine","azul-seguros","allianz","hdi","bradesco-seguros","itau-seguros"];
const insurerNames = ["MAPFRE","Suhai","Yelum","Porto","Tokio Marine","Azul Seguros","Allianz","HDI","Bradesco Seguros","Itaú Seguros"];
const faqs = [
  ["Por que contratar com a Vital?","Porque entendemos seu perfil, comparamos as alternativas e continuamos ao seu lado depois da contratação."],
  ["A Vital atende toda Minas Gerais?","Sim. Atendemos todo o estado de forma 100% online, com contato humano e suporte próximo."],
  ["Como vocês encontram a melhor opção?","Analisamos preço, coberturas, franquias, limites, assistências e a qualidade de atendimento de cada seguradora."],
  ["A opção mais barata pode ser uma boa escolha?","Pode, desde que ofereça a proteção necessária. Nosso trabalho é equilibrar preço e cobertura sem excessos."],
  ["A Vital acompanha depois da contratação?","Sim. Ajudamos em alterações, documentos, assistências e acompanhamento de sinistros."],
];

function WhatsIcon(){return <svg className="whats-icon" viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M16 3A13 13 0 0 0 4.8 22.6L3 29l6.6-1.7A13 13 0 1 0 16 3Zm0 23.6c-2 0-3.9-.5-5.5-1.5l-.4-.2-3.9 1 1.1-3.8-.3-.4A10.6 10.6 0 1 1 16 26.6Zm5.8-7.9c-.3-.2-1.9-.9-2.2-1s-.5-.2-.7.2-.8 1-1 1.2-.4.2-.7.1a8.7 8.7 0 0 1-2.6-1.6 9.8 9.8 0 0 1-1.8-2.3c-.2-.3 0-.5.1-.7l.5-.6.3-.6c.1-.2 0-.4 0-.6s-.7-1.7-1-2.3c-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.4-1.2 1.2-1.2 2.9s1.2 3.3 1.4 3.5c.2.2 2.4 3.7 5.9 5.2.8.4 1.5.6 2 .7.8.3 1.6.2 2.2.1.7-.1 1.9-.8 2.2-1.5.3-.7.3-1.3.2-1.5-.1-.1-.4-.3-.7-.4Z"/></svg>}
function HomeCTA({children}:{children:React.ReactNode}){return <WhatsAppLink className="home-primary" href={whatsapp} target="_blank" rel="noreferrer"><WhatsIcon/>{children}</WhatsAppLink>}

export default function Home(){return <main className="home-page">
  <header className="home-header"><div className="home-shell home-header-inner">
    <a className="home-brand" href="#inicio" aria-label="Vital Corretora - início"><img src="/vital-lettering.png" alt="Vital"/><span>Corretora de Seguros,<br/>Consórcios &amp; Planos de Saúde</span></a>
    <nav aria-label="Navegação principal"><a href="#produtos">Produtos</a><a href="/seguro-automovel/">Seguro Auto</a><a href="#sobre">Sobre a Vital</a></nav>
    <WhatsAppLink className="home-header-cta" href={whatsapp} target="_blank" rel="noreferrer"><WhatsIcon/>Falar com a Vital</WhatsAppLink>
  </div></header>
  <section className="home-hero" id="inicio">
    <img className="home-hero-bg" src="/home-hero-v1.png" alt="Felipe Vital com soluções para veículos, imóveis, máquinas e transportes"/><div className="home-hero-shade"/>
    <div className="home-shell home-hero-content"><span className="home-kicker">Seguros, consórcios e planos de saúde</span><h1>Proteção para tudo o que é <em>Vital.</em></h1><p>Cuidamos de pessoas, famílias e empresas com soluções bem escolhidas, atendimento próximo e proteção do tamanho certo.</p><div className="home-hero-actions"><WhatsAppLink className="home-primary" href={whatsapp} target="_blank" rel="noreferrer"><WhatsIcon/>Falar com um especialista</WhatsAppLink><a className="home-secondary" href="#produtos">Conhecer o portfólio <span>↓</span></a></div></div>
  </section>
  <section className="home-products" id="produtos"><div className="home-shell">
    <header className="home-section-heading"><div><span>Soluções para cada momento</span><h2>Nosso Portfólio<br/>de Produtos</h2></div><p>Escolha uma categoria para conhecer a proteção indicada. Cada solução terá sua própria página de detalhes.</p></header>
    <div className="home-product-grid">{products.map(([title,image,href,text],index)=><a className="home-product-card" href={href} key={title} aria-label={`Conhecer ${title}`}><div className="home-product-image"><img src={image} alt=""/><span>{String(index+1).padStart(2,"0")}</span></div><div className="home-product-copy"><h3>{title}</h3><p>{text}</p><b>Conhecer solução <i>↗</i></b></div></a>)}</div>
  </div></section>
  <section className="manifest home-comparison" id="diferenciais"><img className="manifest-watermark" src="/vital-shield.png" alt="" aria-hidden="true"/><div className="shell manifest-content"><div className="manifest-heading"><span>Seguro pensado para você</span><h2>Estruturamos sua apólice <em>do jeito certo.</em></h2><p>Proteção suficiente para o que realmente importa, sem riscos exagerados ou coberturas que você não precisa.</p></div><div className="comparison-grid"><article className="comparison-card comparison-us"><div className="comparison-label"><b>NÓS</b><span>Vital Corretora</span></div><ul><li><i>✓</i><span><strong>Foco no cliente</strong><small>Entendemos seu perfil antes de cotar.</small></span></li><li><i>✓</i><span><strong>Sem riscos excessivos</strong><small>Limites ajustados à sua realidade.</small></span></li><li><i>✓</i><span><strong>Zero coberturas desnecessárias</strong><small>Você paga pelo que realmente faz sentido.</small></span></li><li><i>✓</i><span><strong>Melhores condições</strong><small>Comparamos seguradoras, preços e franquias.</small></span></li></ul></article><article className="comparison-card comparison-them"><div className="comparison-label"><b>ELES</b><span>Venda sem análise</span></div><ul><li><i>×</i><span><strong>Foco em comissão</strong><small>A proposta atende mais à venda do que ao cliente.</small></span></li><li><i>×</i><span><strong>Riscos exagerados</strong><small>Limites maiores sem necessidade real.</small></span></li><li><i>×</i><span><strong>Coberturas inúteis</strong><small>Itens que encarecem e pouco protegem.</small></span></li><li><i>×</i><span><strong>Preços maiores</strong><small>Sem comparação transparente entre opções.</small></span></li></ul></article></div></div></section>
  <section className="insurers home-insurers" id="seguradoras"><img className="insurers-shield" src="/vital-shield.png" alt="" aria-hidden="true"/><div className="shell insurer-heading"><div><span>Uma cotação. Várias possibilidades.</span><h2>As principais seguradoras competindo pela sua escolha.</h2></div><p>Comparamos preço, franquia, assistência, rede de atendimento e coberturas para mostrar o que muda de verdade.</p></div><div className="logo-marquee" aria-label="Seguradoras parceiras"><div className="logo-strip">{[0,1].map(group=><div className="logo-set" key={group} aria-hidden={group===1}>{insurerLogos.map((slug,index)=><div className="insurer-logo" key={`${group}-${slug}`}><img src={`/insurers/${slug}.png`} alt={group===0?insurerNames[index]:""}/></div>)}</div>)}</div></div></section>
  <section className="method home-method" id="processo"><div className="shell"><div className="section-heading centered"><span>Simples do começo ao fim</span><h2>Seu seguro em apenas 3 passos.</h2></div><div className="steps"><article><b>01</b><h3>Conte o que precisa proteger</h3><p>Você envia os dados básicos e explica sua necessidade.</p></article><article><b>02</b><h3>A Vital faz o trabalho</h3><p>Comparamos propostas, coberturas, limites e condições.</p></article><article><b>03</b><h3>Você escolhe com clareza</h3><p>Explicamos as diferenças e você contrata a melhor opção.</p></article></div><div className="centered"><HomeCTA>Começar minha cotação</HomeCTA></div></div></section>
  <section className="region home-region" id="minas-gerais"><svg className="region-shield" viewBox="0 0 500 590" aria-hidden="true"><path d="M250 20C185 70 111 97 42 109v173c0 137 78 238 208 288 130-50 208-151 208-288V109C389 97 315 70 250 20Z"/></svg><div className="shell region-content"><div className="region-copy"><span>Vital em toda Minas Gerais</span><h2>Do Sul de Minas para todo o estado.</h2><p>Somos referência no Sul de Minas e atendemos todo o estado de forma 100% online, com a mesma proximidade, segurança e suporte humano de um atendimento presencial.</p><div className="region-assurance"><b>Sem distância no atendimento.</b><small>Cotação, contratação e suporte com acompanhamento de verdade, onde você estiver.</small></div><HomeCTA>Falar com a Vital</HomeCTA></div><div className="region-map" aria-label="Atendimento em todo o estado de Minas Gerais"><div className="mg-map-image" role="img" aria-label="Mapa de Minas Gerais"><div className="mg-silhouette"/><span className="pin pin-1"/><span className="pin pin-2"/><span className="pin pin-3"/><span className="pin pin-4"/><span className="pin pin-5"/><span className="pin pin-6"/></div><div className="map-caption"><strong>Minas Gerais inteira</strong><span>Atendimento humano, ágil e 100% online</span></div></div><div className="region-benefits"><article><b>01</b><i>◉</i><h3>Acompanhamento integral de sinistros</h3></article><article><b>02</b><i>↗</i><h3>Bônus progressivos em apólices</h3></article><article><b>03</b><i>◷</i><h3>Atendimento ágil, 7 dias por semana, 24 horas</h3></article><article><b>04</b><i>▤</i><h3>Suporte em endossos, perícias e documentos</h3></article></div></div></section>
  <section className="faq home-faq" id="duvidas"><div className="shell faq-grid"><div><span>Antes, durante e depois</span><h2>Você protegido em toda a jornada.</h2><p>A Vital entende antes, orienta durante a escolha e continua ao seu lado depois da contratação.</p><HomeCTA>Falar com um especialista</HomeCTA></div><div className="questions">{faqs.map(([question,answer])=><details key={question}><summary>{question}<span>⌄</span></summary><p>{answer}</p></details>)}</div></div></section>
  <section className="home-about" id="sobre"><div className="home-shell home-about-grid"><div><span>Todo cuidado é Vital</span><h2>Uma corretora presente antes, durante e depois.</h2></div><div><p>Entendemos sua realidade, comparamos as melhores alternativas e explicamos cada escolha com clareza. Depois da contratação, seguimos ao seu lado em alterações, assistências e sinistros.</p><WhatsAppLink className="home-primary" href={whatsapp} target="_blank" rel="noreferrer"><WhatsIcon/>Quero falar com a Vital</WhatsAppLink></div></div></section>
  <footer className="home-footer"><div className="home-shell home-footer-main"><div className="home-brand"><img src="/vital-lettering.png" alt="Vital"/><span>Corretora de Seguros,<br/>Consórcios &amp; Planos de Saúde</span></div><nav><a href="/seguro-automovel/">Seguro Auto</a><a href="/seguro-automovel/blog/">Blog</a><a href="/seguro-automovel/politica-de-privacidade/">Privacidade</a><a href="/seguro-automovel/termos-de-uso/">Termos de Uso</a></nav></div><div className="home-shell home-footer-bottom"><span>Vital Corretora de Seguros · SUSEP 261180251</span><span>Monsenhor Paulo, Minas Gerais</span></div></footer>
  <WhatsAppLink className="home-floating" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Falar com a Vital no WhatsApp"><WhatsIcon/></WhatsAppLink>
</main>}
